### ISSUE TITLE
Electrolaryngeal VC in the current framework

### ISSUE THREAD

**Issue by devanshkhandekar** [HaydenCaffrey/SIG-VC#1]
Hey, Is this repo an extension of the paper "Electrolaryngeal speech enhancement based on a two stage framework with bottleneck feature refinement and voice conversion" ? . If yes , I am interested to know the exact steps to train the model on my custom data. Thank you

**Comment by HaydenCaffrey** [comment]
Hi! Thank you for your interest in our work in electrolaryngeal speech enhancement. Although some basic blocks are similar between these two works, this repository is not an extension of the paper “Electrolaryngeal speech enhancement based on a two-stage framework with bottleneck feature refinement and voice conversion”. Unfortunately, we cannot release the code of that paper due to some restrictions. However, we would be glad to inform you if we release the code in the future.

**Comment by devanshkhandekar** [comment]
> Hi! Thank you for your interest in our work in electrolaryngeal speech enhancement. Although some basic blocks are similar between these two works, this repository is not an extension of the paper “Electrolaryngeal speech enhancement based on a two-stage framework with bottleneck feature refinement and voice conversion”. Unfortunately, we cannot release the code of that paper due to some restrictions. However, we would be glad to inform you if we release the code in the future.

Thanks @HaydenCaffrey . The GAN based EL-NL conversion without TTS is definitely a breakthrough work. I'd love to be a part of it. Looking forward to your Open Contributions in the future :)
